# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteomics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterfile',
            name='type',
            field=models.CharField(blank=True, choices=[(b'xtandem default', b'xtandem default')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parameterfile',
            name='file',
            field=models.FileField(upload_to=b'parameter_files'),
        ),
    ]
