# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extensible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTypePlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='modeltypeplugin',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugins.Plugin'),
        ),
        migrations.AddField(
            model_name='modeltypeplugin',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensible.ModelType'),
        ),
        migrations.AlterUniqueTogether(
            name='modeltypeplugin',
            unique_together=set([('type', 'plugin')]),
        ),
    ]
