# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('glims', '0009_lab_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[(b'DAFIS', b'DaFIS Account'), (b'PO', b'Purchase Order')], max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='glims.Project')),
            ],
        ),
    ]
