# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('glims', '0013_auto_20160721_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioshareAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bioshare_account', to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='LabShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioshare_id', models.CharField(max_length=15, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glims.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.SlugField()),
                ('labshare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bioshare.LabShare')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='glims.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='projectshare',
            unique_together=set([('labshare', 'folder')]),
        ),
        migrations.AlterUniqueTogether(
            name='labshare',
            unique_together=set([('lab', 'group')]),
        ),
    ]
