# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-02 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioshare', '0002_auto_20160725_2149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labshare',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='labshare',
            name='group',
        ),
        migrations.RemoveField(
            model_name='labshare',
            name='lab',
        ),
        migrations.AddField(
            model_name='projectshare',
            name='bioshare_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='projectshare',
            name='folder',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectshare',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projectshare',
            name='labshare',
        ),
        migrations.DeleteModel(
            name='LabShare',
        ),
    ]
