# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-02 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioshare', '0003_auto_20160902_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectshare',
            name='folder',
        ),
    ]
