# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
