# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0002_run_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='num_lanes',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
