# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20160507_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
