# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-16 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20160507_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(related_name='dependents', to='tasks.Task'),
        ),
    ]
