# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfoproject',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
