# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0002_auto_20160404_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='cloudstore',
        ),
    ]
