# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0006_auto_20160426_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_projects',
            field=models.ManyToManyField(related_name='_project_related_projects_+', to='glims.Project'),
        ),
    ]
