# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0009_lab_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='affiliation',
            field=models.CharField(blank=True, choices=[(b'UCD', b'UC Davis'), (b'UC', b'University of California'), (b'educational', b'Educational'), (b'government', b'Government'), (b'industry', b'Industry'), (b'other', b'Other')], max_length=20, null=True),
        ),
    ]
