# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-24 21:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0011_auto_20160624_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='affiliation',
            field=models.CharField(blank=True, choices=[(b'UC Davis', b'UC Davis'), (b'University of California', b'University of California'), (b'Educational', b'Educational'), (b'Government', b'Government'), (b'Industry', b'Industry'), (b'Other', b'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='sample_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='extensible.ModelType'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='glims.Status'),
        ),
    ]
