# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0012_auto_20160624_2103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together=set([('sample_id', 'project'), ('name', 'project')]),
        ),
    ]
