# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-29 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0013_auto_20160721_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='lab',
            name='affiliation',
            field=models.CharField(blank=True, choices=[(b'UC Davis', b'UC Davis'), (b'University of California', b'University of California'), (b'Educational', b'Educational'), (b'Government', b'Government'), (b'Industry', b'Industry'), (b'Other', b'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='slug',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
