# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-29 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0014_auto_20160729_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
    ]
