# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-29 17:08
from __future__ import unicode_literals

from django.db import migrations, models

def populate_last_name(apps, schema_editor):
    Lab = apps.get_model("glims", "Lab")
    for lab in Lab.objects.filter(last_name='LAST_NAME'):
        lab.last_name = lab.first_name
        lab.first_name = None
        lab.save()

class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0015_auto_20160729_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='last_name',
            field=models.CharField(default='LAST_NAME', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lab',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.RunPython(populate_last_name)
    ]


