# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0018_auto_20160830_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
