# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0020_barcode_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='samples',
        ),
        migrations.AddField(
            model_name='pool',
            name='libraries',
            field=models.ManyToManyField(blank=True, null=True, related_name='pools', to='glims.Library'),
        ),
        migrations.AlterField(
            model_name='library',
            name='barcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='glims.Barcode'),
        ),
        migrations.AlterField(
            model_name='library',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='glims.Sample'),
        ),
    ]
