# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 00:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0023_auto_20161020_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 20, 0, 43, 37, 940452, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
