# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-01 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import glims.models


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0025_auto_20161020_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='affiliation',
            field=models.CharField(blank=True, choices=[(b'UC Davis', b'UC Davis'), (b'University of California', b'University of California'), (b'Educational', b'Educational'), (b'Government', b'Government'), (b'Industry', b'Industry'), (b'Other', b'Other')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='description',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='last_name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='library',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='created',
            field=models.DateField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, db_index=True, default=glims.models.generate_project_id, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sample',
            name='received',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
