# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-03 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0027_auto_20161103_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='glims.Lab'),
        ),
    ]
