# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-16 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0028_auto_20170503_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='libraries',
            field=models.ManyToManyField(related_name='pools', to='glims.Library'),
        ),
    ]
