# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-20 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0029_auto_20170616_1819'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
