# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-24 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0030_auto_20171020_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, default=datetime.datetime(2017, 10, 24, 17, 33, 36, 999991, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
