# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0031_pool_project'),
        ('glims', '0031_project_modified'),
    ]

    operations = [
    ]
