# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extensible', '0003_auto_20171213_1426'),
        ('glims', '0032_merge_20171208_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='adapter',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extensible.ModelSubType'),
        ),
        migrations.AddField(
            model_name='library',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extensible.ModelSubType'),
        ),
        migrations.AddField(
            model_name='pool',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extensible.ModelSubType'),
        ),
        migrations.AddField(
            model_name='project',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extensible.ModelSubType'),
        ),
        migrations.AddField(
            model_name='sample',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extensible.ModelSubType'),
        ),
    ]
