# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
