# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-03 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
