# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-08 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glims', '0028_auto_20170503_2248'),
        ('tracker', '0002_auto_20170503_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='logs',
            field=models.ManyToManyField(to='tracker.Log'),
        ),
        migrations.AddField(
            model_name='log',
            name='project',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='glims.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='export',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
