# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20170508_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(blank=True, choices=[('Billed', 'Billed'), ('Not Billable', 'Not Billable')], max_length=20, null=True),
        ),
    ]
