# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_log_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='logs',
            field=models.ManyToManyField(blank=True, null=True, related_name='exports', to='tracker.Log'),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('Billed', 'Billed'), ('Not Billable', 'Not Billable')], default='Not billed', max_length=20),
        ),
    ]
