# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-16 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20170518_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='status',
        ),
        migrations.AddField(
            model_name='log',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 16, 18, 19, 57, 694760, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='export',
            name='logs',
            field=models.ManyToManyField(related_name='exports', to='tracker.Log'),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('Not billed', 'Not billed'), ('Billed', 'Billed'), ('Not Billable', 'Not Billable')], default='Not billed', max_length=20),
        ),
    ]
